theme: jekyll-theme-slate
title: AZ-400 - Training - Microsoft Azure DevOps Solutions
description: Companion material and resources for the course 'Designing and Implementing Microsoft DevOps solutions' delivery by Ricardo Cabral 
relative_links:
  enabled: true
  collections: true
include:
  - README.md
